// src/app/layout.tsx
import type { Metadata } from "next";
import React from "react";
import "./globals.css";

//  Mantine imports
import "@mantine/core/styles.css";
import "@mantine/notifications/styles.css";
import { ColorSchemeScript } from "@mantine/core";

//  Page metadata (server area)
export const metadata: Metadata = {
  title: "Woldia University Class Schedule System",
  description: "Generated by Next.js and Mantine UI",
};

//  Client provider wrappers
import MantineClientProvider from "@/app/providers/MantineClientProvider";
import ReduxProvider from "@/app/providers/ReduxProvider";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // 👇 Mantine needs this data attribute for SSR hydration
    <html lang="en" data-mantine-color-scheme="light">
      <head>
        {/* 👇 This syncs color scheme between SSR and client */}
        <ColorSchemeScript defaultColorScheme="light" />
      </head>
      <body className="antialiased">
        {/*  Wrap everything inside the Redux provider first */}
        <ReduxProvider>
          {/*  Then wrap with Mantine provider */}
          <MantineClientProvider>
            {children}
          </MantineClientProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}